openapi: 3.0.0
info:
  title: similarProductEngineAPI
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/product/{productId}/similarids':
    parameters:
      - schema:
          type: string
        name: productId
        in: path
        required: true
    get:
      operationId: get-product-similarids
      summary: Gets the ids of the similar products
      description: Returns the similar products to a given one ordered by similarity
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimilarProducts' 
              
                
components:
  schemas:
    SimilarProducts:
      type: array
      description: 'List of similar product Ids to a given one ordered by similarity'
      minItems: 0
      uniqueItems: true
      items:
        type: string
        examples:
                producId: 1
                value: '[2,3,4]'
      
       
   