openapi: 3.0.0
info:
  title: SimilarProducts
  version: '1.0'
servers:
  - url: 'http://localhost:8080'
paths:
  '/product/{productId}/similar':
    get:
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimilarProducts' 
components:
  schemas:
    SimilarProducts:
      type: array
      description: 'List of similar products to a given one ordered by similarity'
      minItems: 0
      uniqueItems: true
      items:
        $ref: '#/components/schemas/ProductDetail'
    ProductDetail:
      description: 'Product detail'
      type: object
      properties:
        id:
          type: string
          minLength: 1
        name:
          type: string
          minLength: 1
        price:
          type: number
        availability:
          type: boolean
      required:
        - id
        - name
        - price
        - availability